version: '3.8'

services:
  backend:
    build: ./backend-crud-app-shadcn
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/crudshadcn
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    depends_on:
      - mysql

  frontend:
    build: ./frontend-crud-app-shadcn
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: crudshadcn
      MYSQL_ROOT_PASSWORD: ""  # Empty password as per your Spring config
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
