version: '3.8'

services:
  backend:
    build: ./backend-crud-app-shadcn
    ports:
      - "8080:8080"
    container_name: springboot-backend

  frontend:
    build: ./frontend-crud-app-shadcn
    ports:
      - "3000:80"
    container_name: react-frontend
